### ISSUE TITLE
Integrate MVI Kotlin Modules into The Bonsai Project

### ISSUE THREAD

**Issue by africanSuperStar** [The-Bonsai-Network/the-bonsai-network#2]
The MVI Kotlin project on Github in my mind is a great resource for learning how to implement a reactive architecture for The Bonsai Network.

Resource: `https://arkivanov.github.io/MVIKotlin/`

1. Study and integrate the following modules from MVI Kotlin in The Bonsai Network.
1.1. mvikotlin
1.2. mvikotlin-extensions-rx
1.3. mvikotlin-logging
1.4. mvikotlin-main
1.5. essenty

**Comment by arkivanov** [comment]
JFY, `mvikotlin-test-internal` module is considered internal, and should not be normally used.
